#!/usr/bin/env bash
# ADAAD phone start — generated by onboard_phone.py
# Run this to start the governance dashboard.
cd "$(dirname "$0")"

# Load persisted env
[ -f ~/.adaad_phone.env ] && source ~/.adaad_phone.env

export ADAAD_ENV=dev
export CRYOVANT_DEV_MODE=1
export ADAAD_SOULBOUND_KEY="${ADAAD_SOULBOUND_KEY:-2cbacbb768cda63d36d22d9782ce57a3f9d3798611159156644e494804b30a90}"

source .venv/bin/activate 2>/dev/null || true

echo ''
echo '  ADAAD governance dashboard'
echo '  Open in Chrome: http://127.0.0.1:8000'
echo '  Press Ctrl+C to stop.'
echo ''

uvicorn server:app --host 127.0.0.1 --port 8000
