#!/usr/bin/env bash
# ADAAD phone start script
# Run this from inside ~/ADAAD to start the governance dashboard.
#
# Generated by onboard_phone.py. Re-run that script to regenerate.
set -euo pipefail

cd "$(dirname "$0")"

# Load persisted env (soulbound key etc.)
[ -f ~/.adaad_phone.env ] && source ~/.adaad_phone.env

# Required env
export ADAAD_ENV="${ADAAD_ENV:-dev}"
export CRYOVANT_DEV_MODE="${CRYOVANT_DEV_MODE:-1}"
export ADAAD_SOULBOUND_KEY="${ADAAD_SOULBOUND_KEY:-}"

# Generate a soulbound key if not set
if [ -z "$ADAAD_SOULBOUND_KEY" ]; then
  ADAAD_SOULBOUND_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
  echo "ADAAD_SOULBOUND_KEY=\"$ADAAD_SOULBOUND_KEY\"" >> ~/.adaad_phone.env
  export ADAAD_SOULBOUND_KEY
fi

# Activate venv if present
source .venv/bin/activate 2>/dev/null || true

echo ""
echo "  ADAAD Governance Dashboard"
echo "  ─────────────────────────────────────"
echo "  Open in Chrome:  http://127.0.0.1:8000"
echo "  ADAAD_ENV=$ADAAD_ENV"
echo "  CRYOVANT_DEV_MODE=$CRYOVANT_DEV_MODE"
echo "  Press Ctrl+C to stop."
echo ""

# Port 8000 — matches the Aponi UI's hardcoded baseUrl
uvicorn server:app --host 127.0.0.1 --port 8000
