# SPDX-License-Identifier: Apache-2.0
# DORK Knowledge Retriever Module
# Phase 141 · INNOV-47 · Live Knowledge Sync Engine (LKSE)
# Updated: prefers corpus.jsonl over legacy dork_knowledge_base.js
#
# Retrieval strategy (in priority order):
#   1. corpus.jsonl   — live LKSE corpus (generated by sync_dork_corpus.py)
#   2. dork_knowledge_base.js — legacy static KB (fallback only)
#
# Invariants enforced:
#   LKSE-DETERM-0: identical query + corpus → identical result (no randomness)
#   LKSE-SYNC-0  : corpus is preferred when present; stale fallback logs a warning

import json
import logging
import re
from functools import lru_cache
from pathlib import Path

logger = logging.getLogger(__name__)

CORPUS_PATH = Path("data/dork/corpus.jsonl")
KB_PATH = Path("ui/developer/ADAADdev/dork_knowledge_base.js")
CORPUS_MANIFEST_PATH = Path("data/dork/corpus_manifest.json")


# ── Corpus loader (LKSE) ──────────────────────────────────────────────────────


@lru_cache(maxsize=1)
def _load_corpus() -> list:
    if not CORPUS_PATH.exists():
        return []
    try:
        records = []
        for line in CORPUS_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
                if "key" in rec and "answer" in rec:
                    records.append(rec)
            except json.JSONDecodeError:
                continue
        return records
    except OSError:
        return []


def _corpus_manifest() -> dict:
    if not CORPUS_MANIFEST_PATH.exists():
        return {}
    try:
        return json.loads(CORPUS_MANIFEST_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


# ── Legacy KB loader ──────────────────────────────────────────────────────────


@lru_cache(maxsize=1)
def _load_legacy_kb() -> list:
    if not KB_PATH.exists():
        return []
    try:
        raw = KB_PATH.read_text(encoding="utf-8")
    except OSError:
        return []

    records = []
    json_match = re.search(r"const\s+KB\s*=\s*(\[.*?\]);", raw, re.DOTALL)
    if json_match:
        try:
            blob = re.sub(r",\s*([}\]])", r"\1", json_match.group(1))
            parsed = json.loads(blob)
            for item in parsed:
                if isinstance(item, dict) and "key" in item and "answer" in item:
                    records.append({
                        "key": str(item["key"]),
                        "answer": str(item["answer"]),
                        "tags": list(item.get("tags", [])),
                    })
            if records:
                return records
        except (json.JSONDecodeError, ValueError):
            pass

    kb_block = re.search(r"const\s+KB\s*=\s*\[(.*?)\];", raw, re.DOTALL)
    if kb_block:
        for obj in re.finditer(r"\{(.*?)\}", kb_block.group(1), re.DOTALL):
            body = obj.group(1)
            k_m = re.search(r"""key\s*:\s*['"](.+?)['"]""", body)
            a_m = re.search(r"""answer\s*:\s*['"](.+?)['"]""", body, re.DOTALL)
            if k_m and a_m:
                ans = a_m.group(1).replace("\\'", "'").replace('\\"', '"')
                records.append({"key": k_m.group(1), "answer": ans, "tags": []})

    return records


# ── Scoring ───────────────────────────────────────────────────────────────────


def _score_match(query_words: set, record: dict) -> float:
    key_words = set(re.findall(r"\w+", record["key"].lower()))
    tag_words: set = set()
    for tag in record.get("tags", []):
        tag_words.update(re.findall(r"\w+", str(tag).lower()))
    answer_words = set(re.findall(r"\w+", record["answer"].lower()))

    if not key_words:
        return 0.0

    key_overlap = len(query_words & key_words) / len(key_words)
    tag_bonus = (len(query_words & tag_words) / len(tag_words)) * 0.3 if tag_words else 0.0
    answer_bonus = min(len(query_words & answer_words) / max(len(answer_words), 1), 0.1)
    confidence = float(record.get("confidence", 0.95))
    return (key_overlap + tag_bonus + answer_bonus) * confidence


def _select_source():
    corpus = _load_corpus()
    if corpus:
        manifest = _corpus_manifest()
        if manifest:
            logger.debug(
                "LKSE corpus loaded: %d entries · phase=%s · version=%s",
                len(corpus),
                manifest.get("source_phase"),
                manifest.get("source_version"),
            )
        return corpus, "corpus"

    logger.warning(
        "LKSE-SYNC-0: corpus.jsonl not found at %s — falling back to legacy KB. "
        "Run scripts/sync_dork_corpus.py to generate corpus.",
        CORPUS_PATH,
    )
    return _load_legacy_kb(), "legacy-kb"


# ── Public API ────────────────────────────────────────────────────────────────


def get_kb_matches(query: str, threshold: float = 0.35, top_n: int = 1):
    """
    Retrieve the best-scoring record for the given query.
    Prefers LKSE corpus.jsonl; falls back to legacy dork_knowledge_base.js.
    Returns {score, answer, key, source} or None.
    """
    records, source = _select_source()
    if not records:
        return None

    query_words = set(re.findall(r"\w+", query.lower()))
    if not query_words:
        return None

    scored = []
    for record in records:
        s = _score_match(query_words, record)
        if s > 0:
            scored.append((s, record))

    if not scored:
        return None

    scored.sort(key=lambda x: x[0], reverse=True)
    best_score, best_record = scored[0]

    if best_score < threshold:
        return None

    return {
        "score": round(best_score, 4),
        "key": best_record["key"],
        "answer": best_record["answer"],
        "source": source,
    }


def get_kb_top_n(query: str, threshold: float = 0.35, top_n: int = 3) -> list:
    """
    Return the top_n records above threshold, sorted by descending score.
    Prefers LKSE corpus.jsonl; falls back to legacy KB.
    """
    records, source = _select_source()
    if not records:
        return []

    query_words = set(re.findall(r"\w+", query.lower()))
    if not query_words:
        return []

    scored = []
    for record in records:
        s = _score_match(query_words, record)
        if s >= threshold:
            scored.append({
                "score": round(s, 4),
                "key": record["key"],
                "answer": record["answer"],
                "source": source,
            })

    scored.sort(key=lambda x: x["score"], reverse=True)
    return scored[:top_n]


def get_corpus_status() -> dict:
    """Return metadata about the active corpus source for DORK health-check."""
    corpus = _load_corpus()
    if corpus:
        manifest = _corpus_manifest()
        return {
            "source": "corpus",
            "path": str(CORPUS_PATH),
            "entry_count": len(corpus),
            "source_phase": manifest.get("source_phase"),
            "source_version": manifest.get("source_version"),
            "generated_at_utc": manifest.get("generated_at_utc"),
            "chain_digest": manifest.get("chain_digest"),
        }
    legacy = _load_legacy_kb()
    return {
        "source": "legacy-kb",
        "path": str(KB_PATH),
        "entry_count": len(legacy),
        "source_phase": None,
        "source_version": None,
        "generated_at_utc": None,
        "chain_digest": None,
    }


def invalidate_kb_cache() -> None:
    """Invalidate in-process KB caches. Useful after corpus hot-reload in tests."""
    _load_corpus.cache_clear()
    _load_legacy_kb.cache_clear()
