#!/usr/bin/env bash
# =============================================================================
# "Geography of Ash" → American Shame Tapestry (HYPER-AGGRESSION)
# Generated by: python scripts/creative/geography_of_ash_pipeline.py --mode advanced
# Extreme stylized glitch, violent kinetic text (primary + ghost/tear layers),
# per-era chromatic aberration seeds, RGB block scramble, frame stutter,
# datamosh-style bursts, maximum destruction film grain.
# =============================================================================

set -euo pipefail

ASSET_DIR="./ash_assets"

AUDIO="${ASSET_DIR}/Geography of Ash.mp3"
BEAST="${ASSET_DIR}/grok-video-f7fb01e1-2c25-49fb-99a0-aa473c9e96a5.mp4"
BASE="${ASSET_DIR}/image.png"

GREENWOOD="${ASSET_DIR}/greenwood_fire.png"
FLIGHT="${ASSET_DIR}/flight_655.mp4"
HALLWAY="${ASSET_DIR}/boarding_school_hallway.png"
OIL="${ASSET_DIR}/oil_rig.png"
ANCESTORS="${ASSET_DIR}/ancestor_portraits.png"
BUBBLES="${ASSET_DIR}/speech_bubbles_overlay.png"

OUTPUT="american_shame_tapestry_hyper.mp4"

echo "=== Rendering American Shame Tapestry (HYPER-AGGRESSION / EXTREME STYLIZED) ==="

ffmpeg -y \
  -i "$AUDIO" -i "$BEAST" -i "$BASE" \
  -i "$GREENWOOD" -i "$FLIGHT" -i "$HALLWAY" \
  -i "$OIL" -i "$ANCESTORS" -i "$BUBBLES" \
  -filter_complex "
    # === HYPER-STYLIZED SOURCE PREP (maximum per-era destruction + CA seeds) ===
    [2:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,
         zoompan=z='min(zoom+0.00045,1.38)':d=1:x='iw/2-(iw/zoom)/2':y='ih/2-(ih/zoom)/2':s=1920x1080,
         noise=alls=11:alls_seed=3,
         geq='r=r(t+sin(t*2)*1.8):g=g(t+cos(t*1.6)*1.3):b=b(t+sin(t*3.1)*2.1)' [base];

    [3:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,
         zoompan=z='min(zoom+0.0019,2.55)':d=1:x='iw/2-(iw/zoom)/2':y='ih/2-(ih/zoom)/2':s=1920x1080,
         eq=brightness=0.16:contrast=1.72:saturation=1.65:gamma=0.78,
         noise=alls=48:alls_seed=19,
         geq='r=r(t+sin(t*4)*2.4):g=g(t+cos(t*2.9)*1.9):b=b(t+sin(t*5.2)*3.1)' [s1];

    [4:v]scale=1920:1080,
         eq=brightness=-0.19:contrast=1.32:saturation=0.38:gamma=1.35,
         noise=alls=31:alls_seed=11,
         geq='r=r(t+cos(t*3.3)*1.6):g=g(t+sin(t*2.1)*2.7):b=b(t+cos(t*4.8)*1.4)' [s2];

    [5:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,
         zoompan=z='min(zoom+0.0013,2.05)':d=1:x='iw/2-(iw/zoom)/2':y='ih/2-(ih/zoom)/2':s=1920x1080,
         eq=brightness=-0.14:contrast=1.26:saturation=0.48,
         noise=alls=29:alls_seed=27,
         geq='r=r(t+sin(t*5.5)*2.9):g=g(t+cos(t*3.7)*1.5):b=b(t+sin(t*2.4)*3.3)' [s3];

    [6:v]scale=1920:1080,
         eq=brightness=0.11:contrast=1.78:saturation=0.55:gamma=0.81,
         noise=alls=39:alls_seed=63,
         geq='r=r(t+cos(t*2.8)*2.1):g=g(t+sin(t*4.1)*1.8):b=b(t+cos(t*3.9)*2.6)' [s4];

    [7:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,
         eq=brightness=0.09:contrast=1.28:saturation=1.26,
         noise=alls=17:alls_seed=33,
         geq='r=r(t+sin(t*3.9)*1.4):g=g(t+cos(t*2.3)*2.2):b=b(t+sin(t*5.7)*1.7)' [s5];

    [8:v]scale=960:540 [bubbles];
    [1:v]scale=1920:1080 [beast];

    # === VIOLENT STYLIZED GLITCH TRANSITION ENGINE ===
    # Scene 1->2 : high-freq RGB block scramble + stutter burst
    [base][s1]blend=all_mode=average:all_opacity='if(lt(mod(t,0.033),0.016),0.92,0.08)':enable='between(t,63.2,64.9)' [g_p1];
    [g_p1]split=3 [gp1a][gp1b][gp1c];
    [gp1a][gp1b]blend=all_mode=difference:all_opacity=0.6:enable='between(t,63.4,64.6)' [rgb_scramble1];
    [rgb_scramble1][s1]xfade=transition=fade:duration=0.65:offset=64.7 [xf1];

    # Scene 2->3 : frame-stutter + horizontal block displacement + fadeblack
    [xf1][s2]xfade=transition=fade:duration=0.55:offset=128.2 [pre_g2];
    [pre_g2]split [pg2a][pg2b];
    [pg2a][pg2b]blend=all_mode=average:all_opacity='if(between(mod(t,0.028),0,0.014),0.15,0.95)':enable='between(t,128.3,129.1)' [stutter_g2];
    [stutter_g2][s2]xfade=transition=fadeblack:duration=0.7:offset=129.0 [xf2];

    # Scene 3->4 : extreme datamosh-style burst (heavy noise + channel tear)
    [xf2][s3]blend=all_mode=average:all_opacity='if(lt(mod(t,0.027),0.013),0.97,0.11)':enable='between(t,193.1,194.7)' [g_p3];
    [g_p3]split=2 [gp3a][gp3b];
    [gp3a][gp3b]blend=all_mode=addition:all_opacity=0.45:enable='between(t,193.3,194.4)' [tear_g3];
    [tear_g3][s3]xfade=transition=fade:duration=0.6:offset=194.5 [xf3];

    # Scene 4->5 : violent periodic RGB offset + high freq flicker into next
    [xf3][s4]xfade=transition=fade:duration=0.65:offset=258.3 [pre_g4];
    [pre_g4]split=3 [pg4a][pg4b][pg4c];
    [pg4a][pg4b]blend=all_mode=difference:all_opacity='if(lt(mod(t,0.021),0.01),0.88,0.22)':enable='between(t,258.5,260.1)' [rgb_tear_g4];
    [rgb_tear_g4][s4]xfade=transition=fadeblack:duration=0.55:offset=260.0 [xf4];

    # Scene 5 -> Beast climax : longest most corrupted handoff
    [xf4][s5]xfade=transition=fade:duration=0.6:offset=323.4 [pre_g5];
    [pre_g5]split [pg5a][pg5b];
    [pg5a][pg5b]blend=all_mode=average:all_opacity='if(between(mod(t,0.019),0.0,0.0095),0.08,0.94)':enable='between(t,323.6,325.2)' [stutter_final];
    [stutter_final][s5]xfade=transition=fade:duration=0.75:offset=325.1 [xf5];

    [xf5][beast]overlay=0:0:enable='between(t,300,414)' [v6];
    [v6][bubbles]overlay=960:540:enable='between(t,325,414)' [vfinal];

    [0:a][1:a]amix=inputs=2:duration=first:dropout_transition=4[aout]
  " \
  -map "[vfinal]" -map "[aout]" \
  -c:v libx264 -preset slower -crf 17 -pix_fmt yuv420p \
  -c:a aac -b:a 320k \
  -t 414 \
  -vf "
    eq=brightness=0.05:contrast=1.15:saturation=0.82,
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='GREENWOOD 1921':fontcolor=white:fontsize=58:x=(w-text_w)/2+sin(t*8.3)*27:y=78+cos(t*7.1)*14:enable='between(t,7,61)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='GREENWOOD 1921':fontcolor=#FF2222:fontsize=58:x=(w-text_w)/2+sin(t*11.7)*9+3:y=78+cos(t*9.4)*8+2:alpha=0.35:enable='between(t,7,61)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='FLIGHT 655':fontcolor=white:fontsize=57:x=(w-text_w)/2+cos(t*7.9)*24:y=79+sin(t*6.8)*13:enable='between(t,69,126)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='FLIGHT 655':fontcolor=#88DDFF:fontsize=57:x=(w-text_w)/2+cos(t*13.2)*11-4:y=79+sin(t*8.3)*7-3:alpha=0.32:enable='between(t,69,126)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='THE CHILDREN WERE TAKEN':fontcolor=#C5A13B:fontsize=54:x=(w-text_w)/2+sin(t*6.4)*21:y=77:enable='between(t,134,191)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='THE CHILDREN WERE TAKEN':fontcolor=#FFEE00:fontsize=54:x=(w-text_w)/2+sin(t*9.8)*8+2:y=77+cos(t*7.6)*5:alpha=0.28:enable='between(t,134,191)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='THE LAND WAS STOLEN':fontcolor=white:fontsize=53:x=(w-text_w)/2+cos(t*5.9)*19:y=78:enable='between(t,199,256)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='THE LAND WAS STOLEN':fontcolor=#33FFAA:fontsize=53:x=(w-text_w)/2+cos(t*10.4)*7-3:y=78+sin(t*6.1)*4:alpha=0.3:enable='between(t,199,256)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='MEMORY AS WITNESS':fontcolor=#C5A13B:fontsize=60:x=(w-text_w)/2+sin(t*6.8)*18:y=76:enable='between(t,264,321)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='MEMORY AS WITNESS':fontcolor=#FFCC55:fontsize=60:x=(w-text_w)/2+sin(t*12.1)*6+4:y=76+cos(t*8.7)*3:alpha=0.27:enable='between(t,264,321)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='THE DIRT DON'\''T LIE':fontcolor=#00C9A7:fontsize=82:x=(w-text_w)/2:y=h-168:enable='between(t,394,414)',
    drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:text='THE DIRT DON'\''T LIE':fontcolor=#00FFDD:fontsize=82:x=(w-text_w)/2+sin(t*14)*4:y=h-168+cos(t*11)*2:alpha=0.22:enable='between(t,394,414)'
  " \
  "$OUTPUT"

echo ""
echo "✅ HYPER-AGGRESSION (ADVANCED) render complete: $OUTPUT"
echo "Features: MAXIMUM stylized glitch (RGB block scramble + frame stutter + datamosh bursts + CA seeds) + extreme multi-layer kinetic text (primary + violent ghost/tear layers) + per-era destruction"
